-- Exercise 5: Triggers
-- Scenario 1: UpdateCustomerLastModified
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
  BEFORE UPDATE ON Customers
  FOR EACH ROW
BEGIN
  :NEW.LastModified := SYSDATE;
END UpdateCustomerLastModified;
/
-- Scenario 2: AuditLog table and LogTransaction trigger
CREATE TABLE AuditLog (
  AuditID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  SourceTable VARCHAR2(50),
  SourceID    NUMBER,
  AccountID   NUMBER,
  Amount      NUMBER,
  TranType    VARCHAR2(10),
  TranDate    DATE,
  CreatedAt   DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
  AFTER INSERT ON Transactions
  FOR EACH ROW
BEGIN
  INSERT INTO AuditLog(SourceTable, SourceID, AccountID, Amount, TranType, TranDate, CreatedAt)
  VALUES('Transactions', :NEW.TransactionID, :NEW.AccountID, :NEW.Amount, :NEW.TransactionType, :NEW.TransactionDate, SYSDATE);
END LogTransaction;
/
-- Scenario 3: CheckTransactionRules
CREATE OR REPLACE TRIGGER CheckTransactionRules
  BEFORE INSERT ON Transactions
  FOR EACH ROW
DECLARE
  v_balance NUMBER;
BEGIN
  IF UPPER(:NEW.TransactionType) = 'WITHDRAWAL' THEN
    SELECT Balance INTO v_balance FROM Accounts WHERE AccountID = :NEW.AccountID FOR UPDATE;
    IF :NEW.Amount > v_balance THEN
      RAISE_APPLICATION_ERROR(-20003, 'Withdrawal exceeds account balance');
    END IF;
  ELSIF UPPER(:NEW.TransactionType) = 'DEPOSIT' THEN
    IF :NEW.Amount <= 0 THEN
      RAISE_APPLICATION_ERROR(-20004, 'Deposit amount must be positive');
    END IF;
  END IF;
END CheckTransactionRules;
/
